post [new]: created article golang in monad
bukan-kambing/blog pull request #8
Opened 2023-06-23 15:46 UTC by mustafasegf

post for golang in monad article

2023-06-23 15:57 UTC, Ghibranalj requested changes
Small mistakes at first skim

2023-06-23 15:57 UTC, Ghibranalj commented on _posts/2023-06-23-adding_monad_to_golang-mustafasegf.md
> +Before go 1.18, this problem have a hard solution. Since golang don't have generic, we couldn't make a generic container that could accept any type. We could use `interface{}` or reflection, but we'l
loose -> lose

2023-06-23 15:57 UTC, Ghibranalj commented on _posts/2023-06-23-adding_monad_to_golang-mustafasegf.md
> +now, we could make a simple struct for the option like this
captialize N

2023-06-23 15:57 UTC, Ghibranalj commented on _posts/2023-06-23-adding_monad_to_golang-mustafasegf.md
> +and we could make one for result like this
add : maybe?

2023-06-23 15:57 UTC, Ghibranalj commented on _posts/2023-06-23-adding_monad_to_golang-mustafasegf.md
> +after that we just need to implement map, getter, unwrap, and constructor right? well... yeah but that's tedious and thankfully there's already a good golang package called [`samber/mo`](https://gith
capitalize A

2023-06-23 15:57 UTC, Ghibranalj commented on _posts/2023-06-23-adding_monad_to_golang-mustafasegf.md
> +this is a basic golang http server that do migration on start and server post request and add it to database. As you can see, golang need to check on the error, and if it's error then we need to earl
Capitalize T

2023-06-23 15:57 UTC, Ghibranalj commented on _posts/2023-06-23-adding_monad_to_golang-mustafasegf.md
> +at a first glance, this look much more clutered. The reason why becasuse golang right now doesn't have light weight anonymous function declaration. There's an [ongoing proposal](https://github.com/go
capitalize A

2023-06-23 16:22 UTC, dnswd approved these changes
my comments idem with @Ghibranalj but good overall

2023-06-23 16:29 UTC, Ghibranalj approved these changes

2023-06-23 16:29 UTC, Ghibranalj commented
Looks good.
Im just not into the pic. But..... Whatever

2023-06-24 04:37 UTC, mustafasegf commented
> Looks good. Im just not into the pic. But..... Whatever

I do agree, the image is subpar. I'll change it

2023-06-24 05:07 UTC, merged